/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#84cc16',
        'on-surface-variant': '#c1cab0',
        'surface-container': '#171f33',
        'tertiary-fixed': '#acedff',
        'inverse-primary': '#416900',
        'primary-fixed-dim': '#91db2a',
        'error-container': '#93000a',
        'on-secondary': '#003824',
        'on-primary-container': '#315200',
        'inverse-on-surface': '#283044',
        'on-error': '#690005',
        'surface-bright': '#31394d',
        outline: '#8b947d',
        tertiary: '#74e3ff',
        'secondary-fixed': '#6ffbbe',
        'on-secondary-fixed': '#002113',
        'on-primary-fixed': '#102000',
        'tertiary-container': '#37c9e7',
        'on-surface': '#dae2fd',
        'on-background': '#dae2fd',
        'on-primary-fixed-variant': '#304f00',
        'secondary-container': '#00a572',
        background: '#0b1326',
        'outline-variant': '#424936',
        'surface-container-low': '#131b2e',
        'on-tertiary-fixed': '#001f26',
        'on-error-container': '#ffdad6',
        'surface-tint': '#91db2a',
        error: '#ffb4ab',
        'surface-container-high': '#222a3d',
        'on-secondary-fixed-variant': '#005236',
        surface: '#0b1326',
        'on-tertiary': '#003640',
        'secondary-fixed-dim': '#4edea3',
        'inverse-surface': '#dae2fd',
        primary: '#9ee939',
        'on-tertiary-container': '#00515f',
        'surface-container-highest': '#2d3449',
        'on-secondary-container': '#00311f',
        'on-tertiary-fixed-variant': '#004e5c',
        secondary: '#4edea3',
        'tertiary-fixed-dim': '#4cd7f6',
        'surface-container-lowest': '#060e20',
        'primary-fixed': '#acf847',
        'surface-variant': '#2d3449',
        'on-primary': '#1f3700',
        'surface-dim': '#0b1326',
      },
      spacing: {
        'gutter-mobile': '0.75rem',
        'space-xs': '0.25rem',
        margin: '2rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'space-xl': '2.5rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'label-sm': ['Space Grotesk', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'display-stat': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'title-md': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-stat': ['48px', { lineHeight: '52px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
